### ISSUE TITLE
What happened to the screencasts?

### ISSUE THREAD

**Issue by bucaran** [fuelphp/docs#1]
Is there anywhere someone can access the screencasts that [used](http://fuelphp.com/discover/screencasts) to be posted on the site?

**Comment by stevewest** [comment]
Screen casts? I don't think there have ever been any on the website, certainly not in my ~2 years of involvement with the framework.

**Comment by bucaran** [comment]
I see. Then please have a look at this http://fuelphp.com/discover/screencasts

**Comment by stevewest** [comment]
I see what you mean. I also notice you have opened this issue on the wrong repo. Please can you raise the issue on https://github.com/fuel/docs and reference this one.

**Comment by bucaran** [comment]
What is the difference between FuelPHP and Fuel? Thanks

**Comment by stevewest** [comment]
FuelPHP contains the v2 packages, whilst Fuel are the older v1 packages.

**Comment by WanWizard** [comment]
The screencasts were made by Phil early 2011, and hosted on some video site. That site removed them, Phil was no longer a team member, and didn't have backups or couldn't be bothered. So they were gone.

**Comment by bucaran** [comment]
Gotcha. :+1: 

Question: Honestly how active is FuelPHP development these days? Are you guys actively working on new stuff or just maintaining the product? 

Cheers.

**Comment by WanWizard** [comment]
Fuel v1 is in maintenance mode, Fuel v2 is actively developed. 

Not as actively as we'd hoped at the moment, we're short on developers, mainly due to a long running illness of both Steve and myself. Since Mark joined we've managed to pick up the pace again.

**Comment by bucaran** [comment]
Fair enough. :+1:
